dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
outpkg: mocks
with-expecter: true
packages:
  github.com/c2fo/vfs/backend/ftp/types:
    config:
      all: true
      dir: "mocks"
